
configserver: true

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
    metadataMap:
      instanceId: ${vcap.application.instance_id:${spring.application.name}:${server.port:8080}}
  client:
    serviceUrl:
      defaultZone: ${vcap.services.config-server.credentials.uri:https:/127.0.0.1:8761}/eureka/

---
spring:
  profiles: cloud
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server-excludable-memorizer.run.aws-usw02-pr.ice.predix.io/eureka/
